### PR TITLE
Add DB Migration Extension Point

### PR DESCRIPTION
**Pull request by PatrickAdelberger**
Adds the DB Migration Extension Point and the reversion file to create the schema, table, and sequence.

### CODE REVIEW

**Review by keckelt — APPROVED** [review]
It runs, so I guess it is fine 🤷 😅

**Comment by PatrickAdelberger** [comment]
@anita-steiner Did you test the DB migration? Can we merge the PR?

**Comment by anita-steiner** [comment]
@PatrickAdelberger please take a look of already existing databases because there you have to generate the migration table and have to add the migration version

**Comment by PatrickAdelberger** [comment]
Okay, thanks I will take a look.

**Comment by PatrickAdelberger** [comment]
I updated the public DB and Anita created the BI DB. 
Which means the branch can be merged

**Pull request merged**
