### PR TITLE
Plugin Consolidation

### PR DESCRIPTION
**Pull request by dvvanessastoiber**
Closes https://github.com/datavisyn/visyn2025/issues/105

### CODE REVIEW

**Comment by keckelt** [comment]
useAsync is now part of tdp_core: https://github.com/Caleydo/ordino/pull/342

**Comment by dvvanessastoiber** [comment]
> CircleCI build fails:
> 
> ```
> > coral@1.0.1-SNAPSHOT compile /home/circleci/phovea-web
> > tsc
> 
> src/menu/DatasetCard.tsx:3:23 - error TS2305: Module '"../../node_modules/ordino/dist"' has no exported member 'useAsync'.
> 
> 3 import {NamedSetList, useAsync, OrdinoContext} from 'ordino';
>                         ~~~~~~~~
> 
> src/pages/components/SourceCodeCard.tsx:1:9 - error TS2305: Module '"../../../node_modules/ordino/dist"' has no exported member 'useAsync'.
> 
> 1 import {useAsync} from 'ordino';
> ```
> 
> useAsync is now part of tdp_core: [Caleydo/ordino#342](https://github.com/Caleydo/ordino/pull/342)

Thank you for your help :)

**Comment by keckelt** [comment]
Thanks for _your_ help 😉

**Review by keckelt — APPROVED** [review]
okay

**Pull request merged**
